service: myodr-lambda  # Serverless 프로젝트 이름

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  memorySize: 128
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - lambda:InvokeFunction
      Resource: "*"

functions:
  createEvent:
    handler: createEvent.handler
    events:
      - http:
          path: create-event
          method: post

  createOrder:
    handler: createOrder.handler
    events:
      - http:
          path: create-order
          method: post

  createProduct:
    handler: createProduct.handler
    events:
      - http:
          path: create-product
          method: post

  getEvent:
    handler: getEvent.handler
    events:
      - http:
          path: get-event/{event_id}
          method: get

  getEventPage:
    handler: getEventPage.handler
    events:
      - http:
          path: getEventPage/{event_key}
          method: get

  viewOrder:
    handler: viewOrder.handler
    events:
      - http:
          path: view-order/{event_no}
          method: get

plugins:
  - serverless-offline  # 로컬 테스트용 플러그인 (선택)
