service: myodr-lambda  # Serverless 프로젝트 이름

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  apiGateway:
    binary:
      types:
        - multipart/form-data
  memorySize: 512
  timeout: 10
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - lambda:InvokeFunction
      Resource: "*"

functions:
  uploadImage:
    handler: uploadImage.handler
    layers:
      - arn:aws:lambda:ap-northeast-2:471112978667:layer:node-sharp:1
    events:
      - http:
          path: admin/uploadImage
          method: post

  createEvent:
    handler: createEvent.handler
    events:
      - http:
          path: admin/createEvent
          method: post

  createOrder:
    handler: createOrder.handler
    events:
      - http:
          path: createOrder
          method: post

  createProduct:
    handler: createProduct.handler
    events:
      - http:
          path: createProduct
          method: post

  getEvent:
    handler: getEvent.handler
    events:
      - http:
          path: getEvent/{event_id}
          method: get

  getEventPage:
    handler: getEventPage.handler
    events:
      - http:
          path: getEventPage/{event_key}
          method: get
      - http:
          path: /{event_key}
          method: get

  viewOrder:
    handler: viewOrder.handler
    events:
      - http:
          path: viewOrder/{event_no}
          method: get
      - http:
          path: viewOrder/{event_no}/{order_id}
          method: get

  adminOrderStatus:
    handler: adminOrderStatus.handler
    events:
      - http:
          path: admin/orders
          method: get
          request:
            parameters:
              querystrings:
                eventId: true
                sellerId: true
                token: false
                scrollTo: false

  updateOrderStatus:
    handler: updateOrderStatus.handler
    events:
      - http:
          path: admin/updateOrder
          method: post


  createEventPage:
    handler: createEventPage.handler
    events:
      - http:
          path: admin/createEvent
          method: get

plugins:
  - serverless-offline  # 로컬 테스트용 플러그인 (선택)
