service: myodr-lambda  # Serverless 프로젝트 이름

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  memorySize: 128
  timeout: 10
#  profile: ${opt:aws-profile, env:AWS_PROFILE, 'ehrdkb2'}  # 로컬에서는 ehrdkb2 프로필 사용
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - lambda:InvokeFunction
      Resource: "*"

functions:
  createEvent:
    handler: createEvent.handler
    events:
      - http:
          path: create-event
          method: post

  createOrder:
    handler: createOrder.handler
    events:
      - http:
          path: create-order
          method: post

  createProduct:
    handler: createProduct.handler
    events:
      - http:
          path: create-product
          method: post

  getEvent:
    handler: getEvent.handler
    events:
      - http:
          path: get-event/{event_id}
          method: get

  getEventPage:
    handler: getEventPage.handler
    events:
      - http:
          path: get-event-page/{event_id}
          method: get

plugins:
  - serverless-offline  # 로컬 테스트용 플러그인 (선택)

package:
  exclude:
    - node_modules/aws-sdk/**  # AWS Lambda 환경에서는 기본 제공됨
