name: Deploy AWS Lambda with Serverless Framework

on:
  push:
    branches:
      - main
    paths:
      - 'backend/lambda/**'

jobs:
  deploy:
    name: Deploy AWS Lambda with Serverless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: backend/lambda
        run: npm install

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Remove broken stack
        run: serverless remove --stage dev || echo "No stack to remove"

      - name: Deploy to AWS using Serverless..
        working-directory: backend/lambda
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
